---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data


```{r preparingData, message=FALSE}
library(dplyr)
library(ggplot2)

# setwd("C:/Users/dlanger/Documents/GitHub/RepData_PeerAssessment1")
dataZipFilePath = "./activity.zip"
dataFilePath <- unzip(dataZipFilePath)
data <- read.csv(dataFilePath)

data$date <- as.Date(data$date, format = "%Y-%m-%d") # Type-cast dates to data type "Date".
#library(lubridate)
#data$date <- ymd(data$date)
```

## What is mean total number of steps taken per day?

```{r stepsPerDay}
data2 <- filter(data, !is.na(steps)) %>%
      group_by(date) %>%
      summarize(totalDailySteps = sum(steps))

ggplot(data2, aes(x = totalDailySteps)) + 
      geom_histogram(binwidth=1000, fill = "cornsilk", colour = "black")

mean(data2$totalDailySteps)
median(data2$totalDailySteps)
```

## What is the average daily activity pattern?

```{r activityPattern}
data3 <- filter(data, !is.na(steps)) %>%
      group_by(interval) %>%
      summarize(meanSteps = mean(steps))

ggplot(data3, aes(x = interval, y = meanSteps)) + 
      geom_line()

data3$interval[which(data3$meanSteps == max(data3$meanSteps))]
```

## Imputing missing values

```{r imputMissingValues}
count(filter(data, is.na(steps)))

naIndices = which(is.na(data$steps))

data4 <- data
data4$steps[naIndices] <- data3$meanSteps[match(data4$interval[naIndices], data3$interval)]

data5 <- group_by(data4, date) %>%
      summarize(totalDailySteps = sum(steps))

ggplot(data5, aes(x = totalDailySteps)) + 
      geom_histogram(binwidth=1000, fill = "cornsilk", colour = "black")

mean(data5$totalDailySteps)
median(data5$totalDailySteps)
```

## Are there differences in activity patterns between weekdays and weekends?

```{r weekdayVsWeekend}
data6 <- data4

data6$weekday <- as.POSIXlt(data$date)$wday
data6$dayType <- factor("weekday", c("weekday", "weekend"), labels = c("weekday", "weekend"))
data6$dayType[data6$weekday %in% c(0, 6)] <- factor("weekend", c("weekday", "weekend"), labels = c("weekday", "weekend"))

data7 <- filter(data6, !is.na(steps)) %>%
      group_by(interval, dayType) %>%
      summarize(meanSteps = mean(steps))

ggplot(data7, aes(x = interval, y = meanSteps)) + 
      geom_line() +
      facet_grid(dayType ~ .)

```
